version: '3.8'

services:
  kcaptcha-solver:
    image: ghcr.io/returntofirst/kcaptcha-solver:latest
    restart: always
    environment:
      - MODEL_FILE_NAME=best_int8.onnx
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./model:/model