version: '3.8'

services:
  kcaptcha-solver:
    image: ghcr.io/returntofirst/kcaptcha-solver:latest
    restart: always
    environment:
      - MODEL_FILE_NAME=best_int8.onnx
    ports:
      - "8000:8000"
    volumes:
      - /k8s/kcaptcha/model:/model