apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcaptcha-solver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcaptcha-solver
  template:
    metadata:
      labels:
        app: kcaptcha-solver
    spec:
      containers:
        - name: kcaptcha-solver
          image: ghcr.io/returntofirst/kcaptcha-solver:latest
          imagePullPolicy: Always
          env:
            - name: MODEL_FILE_NAME
              value: "best_int8.onnx"
            - name: SERVER_HOST # Optional
              value: "0.0.0.0"
            - name: SERVER_PORT # Optional
              value: 8000
            - name: YOLO_CONFIDENCE_THRESHOLD # Optional
              value: 0.5
            - name: YOLO_IOU_THRESHOLD # Optional
              value: 0.5
          volumeMounts:
            - name: model-volume
              mountPath: /model
          ports:
            - containerPort: 8000
      volumes:
        - name: model-volume
          hostPath:
            path: /absolute-path-to-model
            
---
apiVersion: v1
kind: Service
metadata:
  name: kcaptcha-solver
spec:
  type: NodePort
  selector:
    app: kcaptcha-solver
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 8000
